### ISSUE TITLE
Windows compatibility?

### ISSUE THREAD

**Issue by arosen93** [kjappelbaum/mofdscribe#276]
Are you aiming to maintain compatibility for Windows users? If so, it could be worth considering making `raspa2` and `zeopp-lsmo` optional dependencies since they are presumably only needed for specific featurization approaches. Not sure if that's already the case -- I'm only basing this on the `README` since I've yet to dig into the code. Just installing.

**Comment by kjappelbaum** [comment]
closing this as they are optional now and there is now a first iteration of the conda recipe (though still with limited Windows support for some dependencies)
