### ISSUE TITLE
Hosting QMOF Data on MPContribs

### ISSUE THREAD

**Issue by arosen93** [kjappelbaum/mofdscribe#318]
This is to kick off a discussion on how to best handle the QMOF data and how to store the QMOF data all in one place. Currently, data is being pulled from your Dropbox, but I think that a better solution would be to have all QMOF-relevant data hosted on MPContribs, and then we can use the MPContribs Python client to fetch the QMOF data in `mofdscribe`.

It's a bit clunky, but the following code will automatically fetch all the structures and tabulated data for every MOF in the QMOF Database, and it takes about 10 seconds to run.

```python
from mpcontribs.client import Client
from pymatgen.core import Structure

# Instantiate the MPContribs client
apikey = "MyAPIKey" # this is a user's MPContribs API key
client = Client(apikey=apikey, host="contribs-api.materialsproject.org")

# Get the full set of contributions for the QMOF Database project
# Note: The structures returned here are unique identifiers and need to be fetched separately
qmof_entries = client.contributions.get_entries(
    project="qmof", _fields=["identifier", "data", "structures"]
).result()["data"]

# Parse out the tabulated data for each MOF. These are things like bandgap, PLD, etc.
data = [qmof_entry['data'] for qmof_entry in qmof_entries]

# Parse out the unique structure IDs
structure_ids = [entry["structures"][0]["id"] for entry in qmof_entries]

# Get the CIF strings for each structure ID
structure_data = client.structures.get_entries(
    id__in=structure_ids, _fields=["name", "cif"]
).result()["data"]

# Convert CIF strings to structures
structures = [Structure.from_str(entry["cif"], fmt="cif") for entry in structure_data]
```
This would replace a lot of the code in the `__init__` for `QMOFDataset()` but would naturally update with the QMOF Database. On the user's side, the only that would need to change are: 1) They would need to install the `mpcontribs-client` package (can be an optional dependency); 2) They would need to provide their MPContribs API key when they instantiate the `QMOFDataset()`.

What are your thoughts on something like this? If you think this is a good idea, I can work on a PR. The largest piece of work to get done would be to get all the missing data/labels on MPContribs (e.g. the adsorption data) as well as any other new info you've stored in the QMOF Database (e.g. the graph hashes and such), which I can coordinate with an appropriate JSON file.

**Comment by kjappelbaum** [comment]
I guess the only remaining thing is to figure out how to keep it updated (and then, in the longer term, what is the best way for me to help to also display some of the data)

**Comment by arosen93** [comment]
Sounds good. I have a Jupyter notebook that takes in your data on Zenodo and my data on Figshare, organizes it all, and uploads to MPContribs. [I will finalize the MPContribs upload today so it's all up before the pre-print is online]. I can share that with you and then it should be fairly straightforward for either of us to update with any new data. In terms of displaying data, that's a bit up to you and what you'd like/not like to be involved with. It would be nice to have data visible on the Materials Project. If you were interested in getting involved with that, we can add you to the MP web repo and work together to display some of the data, e.g. isotherms. However, that's something I personally wouldn't be able to get involved with for a few months, most likely.

**Comment by kjappelbaum** [comment]
>. If you were interested in getting involved with that, we can add you to the MP web repo and work together to display some of the data, e.g. isotherms. However, that's something I personally wouldn't be able to get involved with for a few months, most likely.

yea, I'd like to get involved. I also do not have a ton of time but could invest 1h/week or so atm

**Comment by kjappelbaum** [comment]
closing this as (at least the first iteration) is solved, thanks again! Will soon come back with an update as I got through all the QMOFs now.
