### ISSUE TITLE
Using RF code, or other non-CIF input, to calculate surface area

### ISSUE THREAD

**Issue by KP-303** [kjappelbaum/mofdscribe#447]
Is it possible to calculate gravimetric surface area (surface area to mass ratio) from some input other than a CIF? For example, the RF code from supramolecular VAE, or from a list of metal centres, linkers and the topology?

I've read the documentation but may have missed this in which case I apologise.

Thanks.

**Comment by kjappelbaum** [comment]
Hi 👋🏽 ,

you'll need the structure's geometry to compute the surface area or any related property. That is, you'd need to assemble your MOF based on the nodes, linkers in a given net and then relax the structure. 

For all featurizers in this library, a crystal structure is the expected input. 

However, I'm open to adding an interface to MOF-assembly tools and simple geometry optimization with LAMMPS

**Comment by KP-303** [comment]
OK thanks. So the only way is to use a .cif file? What about a .mol file or .xyz?

**Comment by KP-303** [comment]
Thanks!

**Comment by kjappelbaum** [comment]
Is there anything else I can help you with? Otherwise, I'd close this issue.

**Comment by KP-303** [comment]
That's fine thanks, sorry, I thought I'd replied a while ago.
